### Onboard my 2018 league
POST http://localhost:8080/onboard
Content-Type: application/json

{
  "leagueId": 517437,
  "season": 2018
}

### Get all teams for my 2018 league
GET http://localhost:8080/team/2018/517437
Accept: application/json

### Get specific team by uuid
GET http://localhost:8080/team/5d2a8016ef19194dfd2b7e1d
Accept: application/json

### Get all roster snapshots for team uuid
GET http://localhost:8080/rostersnap/teamId/5d2a8016ef19194dfd2b7e1d
Accept: application/json

### Get specific roster snapshot by uuid
GET http://localhost:8080/rostersnap/5d2a8023ef19194dfd2b7e81
Accept: application/json

###